// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DeadLetterMessages    string
	MessageProcessingLogs string
	Messages              string
	TenantConfigs         string
	Tenants               string
}{
	DeadLetterMessages:    "dead_letter_messages",
	MessageProcessingLogs: "message_processing_logs",
	Messages:              "messages",
	TenantConfigs:         "tenant_configs",
	Tenants:               "tenants",
}
