// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("DeadLetterMessages", testDeadLetterMessagesUpsert)

	t.Run("MessageProcessingLogs", testMessageProcessingLogsUpsert)

	t.Run("Messages", testMessagesUpsert)

	t.Run("TenantConfigs", testTenantConfigsUpsert)

	t.Run("Tenants", testTenantsUpsert)
}
