// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTenantConfigs(t *testing.T) {
	t.Parallel()

	query := TenantConfigs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTenantConfigsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTenantConfigsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := TenantConfigs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTenantConfigsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TenantConfigSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTenantConfigsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TenantConfigExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if TenantConfig exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TenantConfigExists to return true, but got false.")
	}
}

func testTenantConfigsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	tenantConfigFound, err := FindTenantConfig(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if tenantConfigFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTenantConfigsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = TenantConfigs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTenantConfigsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := TenantConfigs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTenantConfigsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	tenantConfigOne := &TenantConfig{}
	tenantConfigTwo := &TenantConfig{}
	if err = randomize.Struct(seed, tenantConfigOne, tenantConfigDBTypes, false, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}
	if err = randomize.Struct(seed, tenantConfigTwo, tenantConfigDBTypes, false, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = tenantConfigOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tenantConfigTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TenantConfigs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTenantConfigsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	tenantConfigOne := &TenantConfig{}
	tenantConfigTwo := &TenantConfig{}
	if err = randomize.Struct(seed, tenantConfigOne, tenantConfigDBTypes, false, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}
	if err = randomize.Struct(seed, tenantConfigTwo, tenantConfigDBTypes, false, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = tenantConfigOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tenantConfigTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func tenantConfigBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *TenantConfig) error {
	*o = TenantConfig{}
	return nil
}

func tenantConfigAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *TenantConfig) error {
	*o = TenantConfig{}
	return nil
}

func tenantConfigAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *TenantConfig) error {
	*o = TenantConfig{}
	return nil
}

func tenantConfigBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TenantConfig) error {
	*o = TenantConfig{}
	return nil
}

func tenantConfigAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *TenantConfig) error {
	*o = TenantConfig{}
	return nil
}

func tenantConfigBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TenantConfig) error {
	*o = TenantConfig{}
	return nil
}

func tenantConfigAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *TenantConfig) error {
	*o = TenantConfig{}
	return nil
}

func tenantConfigBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TenantConfig) error {
	*o = TenantConfig{}
	return nil
}

func tenantConfigAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *TenantConfig) error {
	*o = TenantConfig{}
	return nil
}

func testTenantConfigsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &TenantConfig{}
	o := &TenantConfig{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, false); err != nil {
		t.Errorf("Unable to randomize TenantConfig object: %s", err)
	}

	AddTenantConfigHook(boil.BeforeInsertHook, tenantConfigBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	tenantConfigBeforeInsertHooks = []TenantConfigHook{}

	AddTenantConfigHook(boil.AfterInsertHook, tenantConfigAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	tenantConfigAfterInsertHooks = []TenantConfigHook{}

	AddTenantConfigHook(boil.AfterSelectHook, tenantConfigAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	tenantConfigAfterSelectHooks = []TenantConfigHook{}

	AddTenantConfigHook(boil.BeforeUpdateHook, tenantConfigBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	tenantConfigBeforeUpdateHooks = []TenantConfigHook{}

	AddTenantConfigHook(boil.AfterUpdateHook, tenantConfigAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	tenantConfigAfterUpdateHooks = []TenantConfigHook{}

	AddTenantConfigHook(boil.BeforeDeleteHook, tenantConfigBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	tenantConfigBeforeDeleteHooks = []TenantConfigHook{}

	AddTenantConfigHook(boil.AfterDeleteHook, tenantConfigAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	tenantConfigAfterDeleteHooks = []TenantConfigHook{}

	AddTenantConfigHook(boil.BeforeUpsertHook, tenantConfigBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	tenantConfigBeforeUpsertHooks = []TenantConfigHook{}

	AddTenantConfigHook(boil.AfterUpsertHook, tenantConfigAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	tenantConfigAfterUpsertHooks = []TenantConfigHook{}
}

func testTenantConfigsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTenantConfigsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(tenantConfigPrimaryKeyColumns, tenantConfigColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTenantConfigToOneTenantUsingTenant(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local TenantConfig
	var foreign Tenant

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, tenantConfigDBTypes, false, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, tenantDBTypes, false, tenantColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tenant struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TenantID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Tenant().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddTenantHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *Tenant) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := TenantConfigSlice{&local}
	if err = local.L.LoadTenant(ctx, tx, false, (*[]*TenantConfig)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Tenant == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Tenant = nil
	if err = local.L.LoadTenant(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Tenant == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testTenantConfigToOneSetOpTenantUsingTenant(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a TenantConfig
	var b, c Tenant

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tenantConfigDBTypes, false, strmangle.SetComplement(tenantConfigPrimaryKeyColumns, tenantConfigColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, tenantDBTypes, false, strmangle.SetComplement(tenantPrimaryKeyColumns, tenantColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tenantDBTypes, false, strmangle.SetComplement(tenantPrimaryKeyColumns, tenantColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Tenant{&b, &c} {
		err = a.SetTenant(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Tenant != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.TenantConfigs[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TenantID != x.ID {
			t.Error("foreign key was wrong value", a.TenantID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TenantID))
		reflect.Indirect(reflect.ValueOf(&a.TenantID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TenantID != x.ID {
			t.Error("foreign key was wrong value", a.TenantID, x.ID)
		}
	}
}

func testTenantConfigsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTenantConfigsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TenantConfigSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTenantConfigsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := TenantConfigs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	tenantConfigDBTypes = map[string]string{`ID`: `uuid`, `TenantID`: `uuid`, `ConfigKey`: `character varying`, `ConfigValue`: `jsonb`, `Version`: `integer`, `IsActive`: `boolean`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_                   = bytes.MinRead
)

func testTenantConfigsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(tenantConfigPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(tenantConfigAllColumns) == len(tenantConfigPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTenantConfigsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(tenantConfigAllColumns) == len(tenantConfigPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &TenantConfig{}
	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tenantConfigDBTypes, true, tenantConfigPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(tenantConfigAllColumns, tenantConfigPrimaryKeyColumns) {
		fields = tenantConfigAllColumns
	} else {
		fields = strmangle.SetComplement(
			tenantConfigAllColumns,
			tenantConfigPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TenantConfigSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTenantConfigsUpsert(t *testing.T) {
	t.Parallel()

	if len(tenantConfigAllColumns) == len(tenantConfigPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := TenantConfig{}
	if err = randomize.Struct(seed, &o, tenantConfigDBTypes, true); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TenantConfig: %s", err)
	}

	count, err := TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, tenantConfigDBTypes, false, tenantConfigPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize TenantConfig struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert TenantConfig: %s", err)
	}

	count, err = TenantConfigs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
